namespace Bedrock.Shared.Enumeration.StringHelper
{
    public enum StringClaimType
    {
        Subject = 1,
        Name = 2,
        GivenName = 3,
        FamilyName = 4,
        MiddleName = 5,
        NickName = 6,
        PreferredUserName = 7,
        Profile = 8,
        Picture = 9,
        WebSite = 10,
        Email = 11,
        EmailVerified = 12,
        Gender = 13,
        BirthDate = 14,
        ZoneInfo = 15,
        Locale = 16,
        PhoneNumber = 17,
        PhoneNumberVerified = 18,
        Address = 19,
        Audience = 20,
        Issuer = 21,
        NotBefore = 22,
        Expiration = 23,
        UpdatedAt = 24,
        IssuedAt = 25,
        AuthenticationMethod = 26,
        SessionId = 27,
        AuthenticationContextClassReference = 28,
        AuthenticationTime = 29,
        AuthorizedParty = 30,
        AccessTokenHash = 31,
        AuthorizationCodeHash = 32,
        Nonce = 33,
        JwtId = 34,
        ClientId = 35,
        Scope = 36,
        Id = 37,
        Secret = 38,
        IdentityProvider = 39,
        Role = 40,
        ReferenceTokenId = 41,
        AuthorizationReturnUrl = 42,
        PartialLoginRestartUrl = 43,
        PartialLoginReturnUrl = 44,
        ExternalProviderUserId = 45,
        PartialLoginResumeId = 46,
        Tenant = 47,
        PasswordExpiry = 48,
        Permission = 49
    }
}
